name: Bug Report
description: Use this template for reporting bugs.
title: "Bug: [Short Description]"
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe your problem in one or two sentences.
      placeholder: The _something function_ produces _some weird error/exception_ when doing _something_ with it.
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code
      description: Add a code snippet that is effected by the bug.
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output
      description: Show the render result/exception if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
